spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/userdb
      database: userdb
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: ''
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: myuser
#    password: mypassword
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  register-with-eureka: true
  fetch-registry: true


logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7


# KeyCloak
keycloak:
  admin:
    username: user
    password: user
    server-url: http://keycloak:8080
    realm: ecom-app
    client-id: admin-cli