spring:
  application:
    name: configserver
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: 30000
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/BITS08SATHYA/configserver.git
#          clone-on-start: true
#          default-label: master
#          search-paths: /config
        native:
          search-locations: classpath:/config



server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true