spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/sathipa/MyCompleteLearning/Spring_Udemy/EmbarkX/Embarx-microservices/configserver/src/main/resources/config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"